---
- name: Assure mesos and marathon services started or stopped on Ubuntu 16.04
  systemd: "{{ item }}"
  with_items:
    - { name: zookeeper, state: restarted, enabled: yes }
    - { name: mesos-slave, state: stopped }
    - { name: mesos-master, state: restarted, enabled: yes }
    - { name: marathon, state: restarted, enabled: yes }
